# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 미래기후
email: info@miraeclimate.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://miraeclimate.com" # the base hostname & protocol for your site
twitter_username: miraeclimate
github_username: miraeclimate

# Build settings
markdown: kramdown

gems: [jekyll-paginate, jekyll-paginate-category]

# pagination
paginate: 1
paginate_file: "posts.html"
paginate_path: "categories/news/page:num"

category_dir: "categories"
category_layout: "posts-layout.html"
